version: '2.1'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8888:8888
      - 5005:5005
    